In [1]:
숫자 배열 :numpy

In [2]:
!pip install numpy

In [6]:
import numpy
my_arr = numpy.arange(1_000_000)
my_arr
print(my_arr)
l = [1,2,3,4]
print(l)

[     0      1      2 ... 999997 999998 999999]
[1, 2, 3, 4]


In [12]:
import numpy as np
my_arr = np.arange(1_000_000) # 0 ~ 999999 , 1차원배열
my_arr
my_arr.shape  # 배열의 크기
my_list = list(range(1_000_000))
print(type(my_list))
print(type(my_arr))
my_arr = np.arange(10) # 0 ~ 9
my_arr

<class 'list'>
<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
data = np.array([0, -3, 6.5]) # 1차원 배열
print(data)
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]]) # 2차원 배열
print(data)
data = np.array([[1.5, -0.1, 3]])
print(data)

[ 0.  -3.   6.5]
[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
[[ 1.5 -0.1  3. ]]


In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # 2행 4열인 2차원배열
arr2 = np.array(data2)
print(arr2)
print(arr2.shape) # (2, 4) : 튜플
#                    0  1
print(arr2.shape[0])
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
2


In [21]:
data1 = [6, 7.5, 8, 0, 1] # 실수 리스트
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # 정수 리스트
print(data1)
arr1 = np.array(data1)
print(arr1)

[6, 7.5, 8, 0, 1]
[6.  7.5 8.  0.  1. ]


In [23]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 1차원 배열 타입은 실수
print(arr1.dtype)
print(arr1)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr2.dtype)
print(arr2)

float64
[1. 2. 3.]
int32
[1 2 3]


In [29]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(arr.dtype)
print(float_arr.dtype)

int64
int64
float64


In [31]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.dtype)
print(arr.astype(np.int32))
print(arr.dtype)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
float64
[ 3 -1 -2  0 12 10]
float64


In [35]:
numeric_strings = np.array(["1.25", "-9.6", "42"])
print(numeric_strings)
numeric_strings = numeric_strings.astype(np.float64)
print(numeric_strings)

['1.25' '-9.6' '42']
[ 1.25 -9.6  42.  ]


In [38]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers.dtype)
converted  = int_array.astype(calibers.dtype)
print(converted.dtype)

[0 1 2 3 4 5 6 7 8 9]
float64
int64


In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr)
result = arr * arr
print(result)
result = arr - arr
print(result)
result = 1 / arr
print(result)
result = arr ** 2
print(result)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [48]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr)
print(arr2)
result = arr2 > arr # 팬시 index
print(result)
print(arr2[[[False,  True, False],[ True, False,  True]]])
print(arr2[result])

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]
[ 4.  7. 12.]
[ 4.  7. 12.]


In [49]:
# indexing, slicing
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [53]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(l[5])
print(l[5:8])
l[5:8] = 12
print(l)

5
[5, 6, 7]


TypeError: must assign iterable to extended slice

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


In [57]:
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [59]:
arr_slice[:] = 64
print(arr_slice)
print(arr)

[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]


In [62]:
arr_slice = arr.copy()
print(arr_slice)
arr_slice[5:8] = 12
print(arr_slice)
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]
[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 64 64 64  8  9]


In [71]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr2d)
print(arr[1:6])
'''
[[1 2 3][4 5 6][7 8 9]]
    0      1      2
         0 1 2
 '''
print(arr2d[1]) # [4 5 6]
                #  0 1 2
print(arr2d[1][1]) # 리스트
print(arr2d[1 , 1]) # [ 행 , 열 ]
print(arr2d[: , 1])
print(arr2d[:2])
print(arr2d[:2, 1:])

[ 0  1  2  3  4 64 64 64  8  9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  2  3  4 64]
[4 5 6]
5
5
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [74]:
lower_dim_slice  = arr2d[1, :2]
print(lower_dim_slice)
print(lower_dim_slice.shape)

[4 5]
(2,)


In [77]:
#  세 번째 열은 선택하고 처음 두 행만 선택
print(arr2d)
print(arr2d[:2 , 2])

print(arr2d[:, :1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1]
 [4]
 [7]]


In [80]:
print(arr2d)
arr2d[:2, 1:] = 0
arr2d

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [81]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [82]:
names == "Bob" # 팬시 index

array([ True, False, False,  True, False, False, False])

In [84]:
print(data)
print(data[[ True, False, False,  True, False, False, False]])
print(data[names == "Bob"])

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[4 7]
 [0 0]]


In [85]:
print(data[names == "Bob"])
print(data[names == "Bob", 1:])
print(data[names == "Bob", 1])

[[4 7]
 [0 0]]
[[7]
 [0]]
[7 0]


In [86]:
# names == "Bob" [ True, False, False,  True, False, False, False]
print(names != "Bob") 
print(~(names == "Bob"))
print(data[~(names == "Bob")])
print(data[[False,  True,  True, False,  True,  True,  True]])

[False  True  True False  True  True  True]
[False  True  True False  True  True  True]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [88]:
cond = names == "Bob" # [ True, False, False,  True, False, False, False]
cond
print(~cond)
print(data[~cond])

[False  True  True False  True  True  True]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [93]:
print(names == "Bob") 
print(names == "Will")
print((names == "Bob") | (names == "Will"))
print(data[(names == "Bob") | (names == "Will")])
mask = (names == "Bob") | (names == "Will")
print(data[mask])

[ True False False  True False False False]
[False False  True False  True False False]
[ True False  True  True  True False False]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


In [96]:
# 0보다 작은 값을 모두 0으로 변경
print(data)
data[data < 0] = 0
print(data)

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


In [98]:
# names이 "Joe" 아닌 팬시 index를 사용해서 data에서 팬시 index에 해당하는 값을 
# 7로 바꾸시오
cond = names != "Joe"
data[cond] = 7
print(data)

[[7 7]
 [0 2]
 [7 7]
 [7 7]
 [7 7]
 [0 0]
 [3 4]]


In [102]:
arr = np.zeros((8, 4))
print(arr)
print(arr[1])
arr[1] = 1
arr[2] = 2
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [104]:
arr = np.zeros((8, 4))
print(arr)
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [107]:
print(arr)
print(arr[4])
print(arr[3])
print(arr[0])
print(arr[6])
print(arr[[4,3,0,6]])
print(arr[[-3, -5, -7]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[4. 4. 4. 4.]
[3. 3. 3. 3.]
[0. 0. 0. 0.]
[6. 6. 6. 6.]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [114]:
arr = np.arange(32)
print(arr)
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1, 5, 7, 2]])
print(arr[[1, 5, 7, 2],[0,3, 1,2]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[ 4 23 29 10]


In [116]:
print(arr[[1, 5, 7, 2]])
print(arr[[1, 5, 7, 2]][: , [0,2,1,3]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  6  5  7]
 [20 22 21 23]
 [28 30 29 31]
 [ 8 10  9 11]]


In [120]:
print(arr)
print()
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[ 4 23 29 10]
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]


In [122]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [125]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
print(arr.T)
result = np.dot(arr.T, arr) #  내적 값
print(result)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[39 20 12]
 [20 14  2]
 [12  2 10]]


In [126]:
result = np.dot(arr.T, arr) #  내적 값
print(result)
result = arr.T @ arr #  내적 값
print(result)

[[39 20 12]
 [20 14  2]
 [12  2 10]]


In [127]:
result = arr.T
print(result)
result = arr.swapaxes(0, 1)
print(result)

[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
