In [ ]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
print(xarr)
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
print(yarr)
cond = np.array([True, False, True, True, False])
print(cond)

In [6]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
rng = np.random.default_rng(seed=12345)
print(rng.random(3))  # 0~1 사이 난수 3개
print(rng.integers(low=0, high=10, size=5)) # 정수 # 0~9 사이 정수 5개

[0.22733602 0.31675834 0.79736546]
[6 6 9 3 8]


In [10]:
arr = rng.standard_normal((4, 4)) # standard_normal:평균이 0 표준편차 1
print(arr)
print(arr > 0)
result = np.where(arr>0 ,  2  ,  -2  )
result

[[-1.22867499  0.25755777  0.31290292 -0.13081169]
 [ 1.26998312 -0.09296246 -0.06615089 -1.10821447]
 [ 0.13595685  1.34707776  0.06114402  0.0709146 ]
 [ 0.43365454  0.27748366  0.53025239  0.53672097]]
[[False  True  True False]
 [ True False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


array([[-2,  2,  2, -2],
       [ 2, -2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [18]:
arr = rng.standard_normal((5, 4))
print(arr)
print(np.mean(arr))
print(arr.mean())
print(np.sum(arr))
print(arr.sum())
print(np.max(arr))
print(arr.max())
print(np.min(arr))
print(arr.min())

[[ 0.2262628   0.68618251  1.21500461  0.21605944]
 [-0.96482356 -0.5566078  -2.29838764 -0.73208213]
 [ 0.7364691   0.46571672 -0.10787605 -0.34143629]
 [ 1.58453379  0.28224121  0.90954639  0.39507157]
 [-0.66937652  1.55536898 -1.23813903 -1.19617346]]
0.008377731597032645
0.008377731597032645
0.1675546319406529
0.1675546319406529
1.584533793470381
1.584533793470381
-2.298387640184483
-2.298387640184483


In [25]:
print(arr.mean(axis = 1)) # 행의 평균
print(arr.max(axis = 1)) # 행
print(arr.mean(axis = 0)) # 열의 평균
print(arr.max(axis = 0)) # 열

[ 0.58587734 -1.13797528  0.18821837  0.79284824 -0.38708001]
[ 1.21500461 -0.5566078   0.7364691   1.58453379  1.55536898]
[ 0.18261312  0.48658032 -0.30397034 -0.33171217]
[1.58453379 1.55536898 1.21500461 0.39507157]


In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr.cumsum()) 
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr.cumsum()) 
print(arr)
print(arr.cumsum(axis = 1)) 
print(arr.cumsum(axis = 0)) 

[ 0  1  3  6 10 15 21 28]
[ 0  1  3  6 10 15 21 28 36]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


In [35]:
arr = rng.standard_normal(100)
print(arr)
print(arr > 0) # boolean : 팬시index : True (1), False (0)
# 양수가 몇개일까요?
print((arr > 0).sum())
print((~(arr > 0)).sum())
print((arr <= 0).sum())

[-0.62369215  0.4874809   0.75900369 -1.47967223  0.12119508  1.18862963
 -0.33343944  0.64909124 -0.02683202  1.02504738  1.84822504 -1.10302841
 -0.29038879  0.3915681  -0.63517949 -0.83004605 -0.34976637 -0.2730431
 -0.65794397  0.32687149  0.80647751  0.74527326  0.67935654  1.19250597
 -1.36682791 -0.1166102   0.18902024  0.52577135 -1.61611005  1.88072206
 -0.89060977  0.26406507  0.73730631  1.08683733 -0.68642576 -0.54180993
  0.3711998   0.58745912  0.91219985 -0.05582628 -0.69384958 -1.33469428
  1.74643808 -1.37337178  0.70120973  0.28006584  0.76438737  0.95651254
  1.35260228 -0.05576757  0.40012833 -1.95141827  0.04876546 -0.90445654
 -0.15026613  1.2414271   0.11071174  1.09518667 -0.19669954  0.40445788
 -0.40899651 -2.54134859 -0.70903455 -0.26158445  0.16263188  0.00800948
 -0.1207063   0.95423778  0.63158305 -0.39150714  0.87854272 -1.97955644
 -0.27577231 -0.14027614  1.3107048  -0.52850065 -1.46383938  0.18565497
  1.70252885 -0.19954437 -0.08885672 -0.19460859  0.

In [41]:
arr = rng.standard_normal(6)
print(arr)
arr.sort()
print(arr)

[ 1.2088434   0.23018634 -0.55780214 -1.14851471  0.38197102  0.7043656 ]
[-1.14851471 -0.55780214  0.23018634  0.38197102  0.7043656   1.2088434 ]


In [44]:
arr = rng.standard_normal((5, 3))
print(arr)
arr.sort()
print(arr)
arr.sort(axis=1) #  행
print(arr)
arr.sort(axis=0) #  행
print(arr)

[[ 0.05808985  0.19741306  1.02838433]
 [ 0.51934022 -0.69504001  0.59370641]
 [ 0.93322266  0.34644167  0.8773103 ]
 [ 0.58894385 -0.23223774 -0.14278637]
 [ 0.61756154 -0.54985719  1.15527732]]
[[ 0.05808985  0.19741306  1.02838433]
 [-0.69504001  0.51934022  0.59370641]
 [ 0.34644167  0.8773103   0.93322266]
 [-0.23223774 -0.14278637  0.58894385]
 [-0.54985719  0.61756154  1.15527732]]
[[ 0.05808985  0.19741306  1.02838433]
 [-0.69504001  0.51934022  0.59370641]
 [ 0.34644167  0.8773103   0.93322266]
 [-0.23223774 -0.14278637  0.58894385]
 [-0.54985719  0.61756154  1.15527732]]
[[-0.69504001 -0.14278637  0.58894385]
 [-0.54985719  0.19741306  0.59370641]
 [-0.23223774  0.51934022  0.93322266]
 [ 0.05808985  0.61756154  1.02838433]
 [ 0.34644167  0.8773103   1.15527732]]


In [45]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
print(np.unique(names))

ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [50]:
unique_sorted_names = list(map(str, np.unique(names)))
print(unique_sorted_names)

['Bob', 'Joe', 'Will']


In [51]:
arr = np.arange(10)
np.save("some_array", arr)

In [52]:
result = np.load("some_array.npy")
result

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.savez("array_archive.npz", a=arr, b=arr)
arch = np.load("array_archive.npz")
print(arch["a"])
print(arch["b"])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
