In [2]:
!pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ------------------ --------------------- 5.8/12.7 MB 28.9 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 31.6 MB/s eta 0:00:00


# NumPy ndarray: 다차원 배열 객체

In [2]:
import numpy as np
my_arr = np.arange(1_000_000)
my_arr
my_arr.shape
my_list = list(range(1_000_000))
print(type(my_list))

<class 'list'>


In [17]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data
data * 10  
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [19]:
data.shape # 
data.dtype

dtype('float64')

# ndarrays 생성

In [23]:
data1 = [6, 7.5, 8, 0, 1]
print(data1)
arr1 = np.array(data1)
print(arr1)

[6, 7.5, 8, 0, 1]
[6.  7.5 8.  0.  1. ]


In [25]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
print(arr2.ndim) # 몇개의 차원인지
print(arr2.shape) # 전체의 차원

2
(2, 4)


In [27]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [32]:
z = np.zeros(10) # 1차원 0행열
print(z)
z = np.zeros((3, 6)) # 2차원 0행렬
print(z)
z = np.empty((2, 3, 2)) # 반 배열 만들기 ( 초기화되지 않은 배열 : 쓰래기 값이 들어 감)
print(z) # 3차원 0행렬

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1.33868360e-311 2.81617418e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.13073288e+277 2.92966904e-033]]

 [[6.50597214e-091 4.08529769e+179]
  [2.32784330e-057 1.53266811e-047]
  [6.48224659e+170 4.93432906e+257]]]


# ndarray의 데이터 유형

In [35]:
np.arange(15) # 0~ 14까지 15개의 값을 갖는다.
num = np.arange(15)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 1차원 배열 타입은 실수
print(arr1.dtype)
print(arr1)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr2.dtype)
print(arr2)

float64
[1. 2. 3.]
int32
[1 2 3]


In [39]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64) # 타입 변경하기
print(float_arr)
print(float_arr.dtype)

int64
[1. 2. 3. 4. 5.]
float64


In [43]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [55]:
numeric_strings = np.array(["1.25", "-9.6", "42"])
print(numeric_strings)
numeric_strings = numeric_strings.astype(np.float64)
print(numeric_strings)

['1.25' '-9.6' '42']
[ 1.25 -9.6  42.  ]


In [61]:
int_array = np.arange(10)
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
converted = int_array.astype(calibers.dtype)
print(converted.dtype)
print(converted)

[0 1 2 3 4 5 6 7 8 9]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [62]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

# NumPy 배열을 사용한 산술

In [66]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
result = arr * arr
print(result)
result = arr - arr
print(result)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [68]:
result = 1 / arr
print(result)
result = arr ** 2
print(result)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [70]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
result = arr2 > arr # 팬시 index
print(result)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


# 기본 인덱싱 및 슬라이싱

In [72]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [75]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[   12 12345    12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [76]:
arr_slice[:] = 64
print(arr_slice)
print(arr)

[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]


In [79]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[2])
print(arr2d[0, 2])
print(arr2d[0][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
3
3


In [102]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [103]:
old_values = arr3d[0].copy()
print(old_values)
arr3d[0] = 42
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [104]:
print(old_values)
print(arr3d[0])
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[42 42 42]
 [42 42 42]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [105]:
arr3d[1, 0]

array([7, 8, 9])

In [106]:
x = arr3d[1]
print(x)
print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


# 슬라이스를 사용한 인덱싱

In [108]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [110]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [112]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [119]:
#  두 번째 행을 선택하고 처음 두 열만 선택
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice)
print(lower_dim_slice.shape)

[4 5]
(2,)


In [122]:
#  세 번째 열은 선택하고 처음 두 행만 선택
print(arr2d)
print(arr2d[:2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]


In [123]:
print(arr2d[:, :1])

[[1]
 [4]
 [7]]


In [124]:
print(arr2d)
arr2d[:2, 1:] = 0
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


# 부울 인덱싱

In [158]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [128]:
print(names == "Bob")

[ True False False  True False False False]


In [159]:
print(data[names == "Bob"])
print()
print(data[[True, False, False,  True, False, False, False]])

[[4 7]
 [0 0]]

[[4 7]
 [0 0]]


In [160]:
print(data[names == "Bob"])
print(data[names == "Bob", 1:])
print(data[names == "Bob", 1])

[[4 7]
 [0 0]]
[[7]
 [0]]
[7 0]


In [161]:
print(names != "Bob")
print(~(names == "Bob"))
print(data[~(names == "Bob")])
print(data[[False,  True,  True, False,  True,  True,  True]])

[False  True  True False  True  True  True]
[False  True  True False  True  True  True]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [162]:
cond = names == "Bob"
print(cond)
print(~cond)
print(data[~cond])
print(data[[False,  True,  True, False,  True,  True,  True]])

[ True False False  True False False False]
[False  True  True False  True  True  True]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [163]:
mask = (names == "Bob") | (names == "Will")
print(mask)
print(data[mask])
print(data[[ True, False,  True,  True,  True, False, False]])

[ True False  True  True  True False False]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


In [164]:
print(data)
data[data < 0] = 0 # 0보다 작은 값을 모두 0으로 변경
print(data)

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


In [165]:
[names != "Joe"]

[array([ True, False,  True,  True,  True, False, False])]

In [166]:
data[names != "Joe"] = 7  # [ True, False,  True,  True,  True, False, False]

In [167]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [169]:
arr = np.zeros((8, 4))
print(arr)
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [170]:
print(arr[[4, 3, 0, 6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [171]:
print(arr[[-3, -5, -7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [175]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print()
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[ 4 23 29 10]


In [176]:
print(arr)
print()
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [177]:
print(arr)
print()
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[ 4 23 29 10]


In [178]:
print(arr)
print("===" * 30)
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]


# 배열 전치 및 축 교체

In [180]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T) # 전치 행렬

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [182]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
print(arr.T)
result = np.dot(arr.T, arr)
print(result)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[39 20 12]
 [20 14  2]
 [12  2 10]]


* [0,0] 위치 (첫 번째 열과 자기 자신)<br />
arr[:,0] # array([ 0,  1,  6, -1,  1])<br />
dot = 0^2 + 1^2 + 6^2 + (-1)^2 + 1^2<br />
    = 0 + 1 + 36 + 1 + 1 = **39<br />
* [0,1] 위치 (1열과 2열)<br />
arr[:,0] # [ 0,  1,  6, -1,  1]<br />
arr[:,1] # [ 1,  2,  3,  0,  0]   <br />
dot = (0)(1) + (1)(2) + (6)(3) + (-1)(0) + (1)(0)<br />
    = 0 + 2 + 18 + 0 + 0 = **20**<br />
* [0,2] 위치 (1열과 3열)<br />
arr[:,0] # [ 0,  1,  6, -1,  1]<br />
arr[:,2] # [ 0, -2,  2, -1,  1]<br />
dot = (0)(0) + (1)(-2) + (6)(2) + (-1)(-1) + (1)(1)<br />
    = 0 -2 +12 +1 +1 = **12**<br />
* [1,0] 위치 (2열과 자기 자신)<br />
arr[:,1] # [ 1,  2,  3,  0,  0]   <br />
arr[:,0] # [ 0,  1,  6, -1,  1]<br />
dot = (0)(1) + (1)(2) + (6)(3) + (-1)(0) + (1)(0)<br />
    = 0 + 2 + 18 + 0 + 0 = **20**<br />
* [1,1] 위치 (2열과 자기 자신)<br />
arr[:,1] # [1, 2, 3, 0, 0]<br />
dot = 1^2 + 2^2 + 3^2 + 0 + 0 = 1 + 4 + 9 = **14**<br />
* [1,2] 위치 <br />
arr[:,1] # [ 1,  2,  3,  0,  0]   <br />
arr[:,2] # [ 0, -2,  2, -1,  1] <br />
dot = 1×0 + 2×(-2) + 3×2 + 0×(-1) + 0×1 = 0 -4 +6 = **2**<br />
* [2:0]<br />
* [2:1]                           <br />                     
* [2,2] 위치<br />
arr[:,2] # [ 0, -2,  2, -1,  1] <br />
dot = 0^2 + (-2)^2 + 2^2 + (-1)^2 + 1^2 = 0 + 4 + 4 + 1 + 1 = **10**<br />
col1 = [ 0,  1,  6, -1,  1]   # arr[:, 0] <br />
col2 = [ 1,  2,  3,  0,  0]   # arr[:, 1] <br />
col3 = [ 0, -2,  2, -1,  1]   # arr[:, 2] <br />
np.dot(arr.T, arr) 는 3×3 행렬이고, 그 안의 각 칸은 두 벡터의 내적값이에요. <br />

| 위치(i, j) | 계산 내용          | 수식                                            |
| -------- | ------------------- | --------------------------------------------- |
| (0, 0)   | col1 ⋅ col1 (자기 자신) | ∑ col1ᵢ² = 0²+1²+6²+(-1)²+1² = **39**         |
| (0, 1)   | col1 ⋅ col2         | 0×1 + 1×2 + 6×3 + (-1)×0 + 1×0 = **20**       |
| (0, 2)   | col1 ⋅ col3         | 0×0 + 1×(-2) + 6×2 + (-1)×(-1) + 1×1 = **12** |
| (1, 1)   | col2 ⋅ col2         | 1² + 2² + 3² = **14**                         |
| (1, 2)   | col2 ⋅ col3         | 1×0 + 2×(-2) + 3×2 = **2**                    |
| (2, 2)   | col3 ⋅ col3         | 0² + (-2)² + 2² + (-1)² + 1² = **10**         |


In [185]:
# @연산자는 행렬 곱셈을 수행하는 또 다른 방법입니다.
result = arr.T @ arr
print(result)

[[39 20 12]
 [20 14  2]
 [12  2 10]]


In [186]:
print(arr)
print(arr.swapaxes(0, 1)) # 전치 행렬  , arr.swapaxes(0, 1) == arr.T
# arr.swapaxes(0, 1)에서 0과 1은 축(axis) 번호입니다.
# axis 0과 axis 1을 서로 바꿈

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]


In [191]:
#  범용 함수 : 유니버설 함수(UFuncs) , 빠른 연상 함수
x =  np.array([1,2,3])
y =  np.array([3,2,1])
result = x + y
print(result)
result = np.add(x,y) 
print(result)

[4 4 4]
[4 4 4]


In [192]:
arr = np.arange(10)
print(np.sqrt(arr)) # np.sqrt(arr) : 제곱근(square root) , 음수일 경우 nan 또는 complex 경고 발생
print(np.exp(arr)) # np.exp(arr) : 자연지수 함수 (e^x) , np.exp(x)는 각 요소 x에 대해 e^x (자연로그 밑 e = 2.71828...)의 거듭제곱을 계산합니다.

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples
# standard_normal는 평균이 0이고 표준편차가 1이되는 행렬을 만들 때 사용

In [194]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
print(x)
print(y)
np.maximum(x, y)

[ 0.78884434 -1.25666813  0.57585751  1.39897899  1.32229806 -0.29969852
  0.90291934 -1.62158273]
[-0.15818926  0.44948393 -1.34360107 -0.08168759  1.72473993  2.61815943
  0.77736134  0.8286332 ]


array([0.78884434, 0.44948393, 0.57585751, 1.39897899, 1.72473993,
       2.61815943, 0.90291934, 0.8286332 ])

In [196]:
arr = rng.standard_normal(7) * 5
print(arr)
# math.modf, 부동 소수점 배열의 분수 부분과 정수 부분을 반환합니다.
np.modf(arr)
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[ 1.28778884  1.56451459 -0.65405845  6.3499156  -0.46481229 -0.33075445
 -5.54107234]
[ 0.28778884  0.56451459 -0.65405845  0.3499156  -0.46481229 -0.33075445
 -0.54107234]
[ 1.  1. -0.  6. -0. -0. -5.]


In [199]:
print(arr)
out = np.zeros_like(arr)
print(out) # 0으로 채워진 arr크기와 type이 같은 배열'
result = np.add(arr, 1)
print(result)
np.add(arr, 1, out=out) # arr의 각 요소에 1을 더한 결과를 out 배열에 저장한다.

[ 1.28778884  1.56451459 -0.65405845  6.3499156  -0.46481229 -0.33075445
 -5.54107234]
[0. 0. 0. 0. 0. 0. 0.]
[ 2.28778884  2.56451459  0.34594155  7.3499156   0.53518771  0.66924555
 -4.54107234]


array([ 2.28778884,  2.56451459,  0.34594155,  7.3499156 ,  0.53518771,
        0.66924555, -4.54107234])

# 조건 논리를 배열 연산으로 표현하기

In [3]:

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
print(xarr)
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
print(yarr)
cond = np.array([True, False, True, True, False])
print(cond)

[1.1 1.2 1.3 1.4 1.5]
[2.1 2.2 2.3 2.4 2.5]
[ True False  True  True False]


In [10]:
result = [float(x if c else y)
    for x, y, c in zip(xarr, yarr, cond)]
# zip(xarr, yarr, cond)은 세 개의 리스트를 동시에 순회하게 해줍니다.
'''
result = []
for x, y, c in zip(xarr, yarr, cond):
    if c:
        result.append(float(x))
    else:
        result.append(float(y))
'''
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [11]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [13]:
# 난수를 생성 시킨다.
# 동일한 시드를 사용하면 같은 난수 순서를 얻게 됩니다.
rng = np.random.default_rng(seed=12345)
print(rng.random(3))  # 0~1 사이 난수 3개
print(rng.integers(low=0, high=10, size=5))  # 0~9 사이 정수 5개

In [14]:
# 모든 양수 값을 2로, 모든 음수 값을 -2로 바꾸
arr = rng.standard_normal((4, 4))
print(arr)
print(arr > 0)
np.where(arr > 0, 2, -2)

[[-1.42382504  1.26372846 -0.87066174 -0.25917323]
 [-0.07534331 -0.74088465 -1.3677927   0.6488928 ]
 [ 0.36105811 -1.95286306  2.34740965  0.96849691]
 [-0.75938718  0.90219827 -0.46695317 -0.06068952]]
[[False  True False False]
 [False False False  True]
 [ True False  True  True]
 [False  True False False]]


In [15]:
np.where(arr > 0, 2, arr)

array([[-1.42382504,  2.        , -0.87066174, -0.25917323],
       [-0.07534331, -0.74088465, -1.3677927 ,  2.        ],
       [ 2.        , -1.95286306,  2.        ,  2.        ],
       [-0.75938718,  2.        , -0.46695317, -0.06068952]])

# 수학적 및 통계적 방법

In [21]:
arr = rng.standard_normal((5, 4)) # "평균 0, 표준편차 1인 정규분포에서 난수를 뽑아 5행 4열의 2차원 배열을 생성해 arr에 저장한다."
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())

[[ 1.62195180e+00 -3.17391946e-01 -8.15814967e-01  3.86579017e-01]
 [-2.23638926e-01 -7.01690809e-01 -1.79571318e+00  8.18325622e-01]
 [-5.71032902e-01  7.85525063e-04 -1.06364272e+00  1.30171450e+00]
 [ 7.47872942e-01  9.80875909e-01 -1.10418688e-01  4.67918531e-01]
 [ 8.90607150e-01  1.02300937e+00  3.12383389e-01 -6.19046857e-02]]
0.14453874667494737
0.14453874667494737
2.8907749334989474


In [24]:
print(arr)
print(arr.mean(axis=1))
print(arr.sum(axis=0))

[[ 1.62195180e+00 -3.17391946e-01 -8.15814967e-01  3.86579017e-01]
 [-2.23638926e-01 -7.01690809e-01 -1.79571318e+00  8.18325622e-01]
 [-5.71032902e-01  7.85525063e-04 -1.06364272e+00  1.30171450e+00]
 [ 7.47872942e-01  9.80875909e-01 -1.10418688e-01  4.67918531e-01]
 [ 8.90607150e-01  1.02300937e+00  3.12383389e-01 -6.19046857e-02]]
[ 0.21883098 -0.47567932 -0.0830439   0.52156217  0.5410238 ]
[ 2.46576006  0.98558805 -3.47320616  2.91263298]


In [26]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr)
print(arr.cumsum())

[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]


In [29]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


# 부울 배열에 대한 메서드

In [36]:
arr = rng.standard_normal(100)
print(arr)
print(arr > 0)
print((arr > 0).sum())
print(arr <= 0)
print((arr <= 0).sum())

[ 1.33140349  1.38554064 -0.0213583  -0.83706473  3.20068942  2.14788244
 -0.10666477 -0.93015494 -0.42367437  0.28096105  1.13155122  0.96938323
  0.4354152  -0.24712573  0.16818521 -0.31062454  0.0709336  -0.1033723
  0.52532528 -1.88267705 -0.34567801 -0.2913092  -1.13063834 -0.17272468
 -1.05354233 -0.66455314 -0.289682   -0.25317177 -0.57378316  1.10347462
  0.20116509  0.32235142  0.23309276 -0.66806524 -0.88321901  0.83963969
 -0.3530779  -1.77113747 -2.1987871   0.22176018 -0.73707721 -0.06758385
 -0.54725416 -0.40741463 -0.17273762 -1.24740736 -0.01876242  0.98612359
  0.69567427 -1.73962463 -1.34163608 -1.33282638 -0.24806882  0.85483479
  0.32298434 -1.75364283  0.05488553  0.80741159 -0.44901398  1.90417969
 -0.6514683   1.17248231  2.35122688 -1.2764236  -0.32368662  0.5746962
  3.21141765 -1.78846554  0.56605023  0.28479635 -0.42237613 -0.83485244
 -0.52591618 -0.30305367 -1.2698595   1.5754851  -1.1084501  -0.42751936
 -0.66148108 -0.41325393  0.09297793 -0.75759707 -0.2

In [37]:
bools = np.array([False, False, True, False])
print(bools.any()) # True가 하나 이상인자
print(bools.all()) # 모두 True인지

True
False


# 정렬

In [38]:
arr = rng.standard_normal(6)
print(arr)
arr.sort()
print(arr)

[-0.91603482 -0.79091899  1.21417311  1.41180344  0.55936443 -1.64489871]
[-1.64489871 -0.91603482 -0.79091899  0.55936443  1.21417311  1.41180344]


In [39]:
arr = rng.standard_normal((5, 3))
print(arr)
arr.sort(axis=0)
print(arr)
arr.sort(axis=1)
print(arr)

[[ 1.57517058  0.3229356  -0.074522  ]
 [ 0.01965488 -0.37268364  1.75834442]
 [ 1.68263067 -1.06481789 -0.18979611]
 [ 0.30340344  1.27573152 -2.42960165]
 [ 0.93061002  1.6678386  -0.33409003]]
[[ 0.01965488 -1.06481789 -2.42960165]
 [ 0.30340344 -0.37268364 -0.33409003]
 [ 0.93061002  0.3229356  -0.18979611]
 [ 1.57517058  1.27573152 -0.074522  ]
 [ 1.68263067  1.6678386   1.75834442]]
[[-2.42960165 -1.06481789  0.01965488]
 [-0.37268364 -0.33409003  0.30340344]
 [-0.18979611  0.3229356   0.93061002]
 [-0.074522    1.27573152  1.57517058]
 [ 1.6678386   1.68263067  1.75834442]]


In [40]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
print(arr2)
print(sorted_arr2)

[  5 -10   7   1   0  -3]
[-10  -3   0   1   5   7]


# 고유 및 기타 집합 논리

In [41]:
# 중복값 재
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
print(np.unique(names))

ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [48]:
unique_sorted_names = list(map(str, np.unique(names)))
print(unique_sorted_names)

['Bob', 'Joe', 'Will']


In [50]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.isin(values, [2, 3, 6]) # 팬시 index를 출력

array([ True, False, False,  True,  True, False,  True])

# 배열을 사용한 파일 입력 및 출력

In [51]:
arr = np.arange(10)
np.save("some_array", arr)

In [52]:
result = np.load("some_array.npy")
result

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.savez("array_archive.npz", a=arr, b=arr) # a=arr, b=arr이기 때문에 같은 배열이 두 번 저장됩니다.
arch = np.load("array_archive.npz")
print(arch["a"])  # 저장된 'a' 배열
print(arch["b"])  # 저장된 'b' 배열

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
