In [1]:
!pip install pandas

# 5   판다 시작하기
## 5.1 pandas 데이터 구조 소개
### 시리즈

In [13]:
import numpy as np
import pandas as pd

In [19]:
obj = pd.Series([4, 7, -5, 3]) # Series 구조
obj
print(obj[1])

7


In [16]:
print(obj.array) # 배열로 
arr = obj.array
print(np.sum(arr)) # numpy로 자동변환 된다.
arr = obj.to_numpy() # numpy 1차원 배
print(arr) 
print(obj.index) # Series의 index가 어떻게 되어 있는지 알 수 있다.

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64
9
[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [17]:
# Series의 index 지정
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [18]:
print(obj2["a"]) # index "a"인 값 출력
obj2["d"] = 6
print(obj2[["c", "a", "d"]])

-5
c    3
a   -5
d    6
dtype: int64


In [23]:
print(obj2)
print(obj2[obj2 > 0])
print(obj2 * 2)
import numpy as np
print(np.sum(obj2)) # Series를 이용해서 numpy연산을 할 경우 자동 형변환이 된다.

d    6
b    7
a   -5
c    3
dtype: int64
d    6
b    7
c    3
dtype: int64
d    12
b    14
a   -10
c     6
dtype: int64
11


In [24]:
print("b" in obj2) # obj2에 "b" index가 있나?
print("e" in obj2)

True
False


In [26]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000} # 딕셔너리
obj3 = pd.Series(sdata) # 딕셔너리로 Series를 만들면 키가 index가 된다.
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
dic = obj3.to_dict() #Series를 딕셔너리로 변환
dic

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [28]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states) # 딕셔너리에서 원하는 키에 해당하는 값만 Series로 변환
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
print(pd.isna(obj4)) #NaN만 True로
print(pd.notna(obj4)) # NaN이 아닌 것만 True로

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool


In [30]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
print(obj3)
print(obj4)
print(obj3 + obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [32]:
obj4.name = "population"  # Series의 이름 부여
obj4.index.name = "state" # Series의 index의 이름부여
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
print(obj)
obj.index = ["Bob", "Steve", "Jeff", "Ryan"] # index변
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64
Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


### 데이터 프레임

In [35]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [36]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
pd.DataFrame(data, columns=["year", "state", "pop"]) # 열의 순서를 변경한다.

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [55]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
print(frame2)
print(frame2.columns) # 열 이름 출력

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [52]:
print(frame2["state"]) # state열의 값 출력
print(frame2.year) # year열이 값 출력

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object
0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64


In [53]:
print(frame2)
print(frame2.loc[1])  # 명시적 index
print(frame2.iloc[2]) # 암시적 index

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN
year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object
year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object


In [56]:
frame2["debt"] = 16.5
print(frame2)
frame2["debt"] = np.arange(6.) # 0   5의 값으로 순차적으로 채워
print(frame2)

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5
   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0


In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
print(val)
frame2["debt"] = val # index가 같은 곳에 Series추가
print(frame2)  

2   -1.2
4   -1.5
5   -1.7
dtype: float64
   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7


In [62]:
print(frame2["state"] == "Ohio")
frame2["eastern"] = frame2["state"] == "Ohio"
print(frame2)

0     True
1     True
2     True
3    False
4    False
5    False
Name: state, dtype: bool
   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False


In [63]:
del frame2["eastern"] # "eastern"열 삭제하기
print(frame2.columns)
print(frame2)

Index(['year', 'state', 'pop', 'debt'], dtype='object')
   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7


In [64]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [65]:
frame3 = pd.DataFrame(populations)
print(frame3)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9


In [67]:
print(frame3.T)

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9


In [68]:
pd.DataFrame(populations, index=[2001, 2002, 2003]) # index를 2001, 2002, 2003으로 20003의 데이터는 없으므로 NaN

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [81]:
print(frame3)
print("==="*20)
print(frame3["Ohio"]) # Series
print("==="*20)
print(frame3["Ohio"][:-1]) # Series의 Slicing
print("==="*20)
print(frame3["Nevada"])
print("==="*20)
print(frame3["Nevada"][:2])

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64
2000    1.5
2001    1.7
Name: Ohio, dtype: float64
2000    NaN
2001    2.4
2002    2.9
Name: Nevada, dtype: float64
2000    NaN
2001    2.4
Name: Nevada, dtype: float64


In [79]:
pdata = {"Ohio": frame3["Ohio"][:-1], 
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [82]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [83]:
frame3.to_numpy() # DataFrame을 numpy 배열로

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [84]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

In [85]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index
print(index)
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')


In [89]:
labels = pd.Index(np.arange(3))
print(labels)
obj2 = pd.Series([1.5, -2.5, 0], index=labels) # series에 index만들어 주기
print(obj2)
print(obj2.index is labels)

Index([0, 1, 2], dtype='int64')
0    1.5
1   -2.5
2    0.0
dtype: float64
True


In [87]:
print(frame3)
print(frame3.columns)
print("Ohio" in frame3.columns)
print(2003 in frame3.index)

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9
Index(['Ohio', 'Nevada'], dtype='object', name='state')
True
False


In [90]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 필수 기능
### Reindexing

In [91]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [93]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"]) # index의 순서를 재 정렬할수 있다.
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [97]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
print(obj3)
reindexed  = obj3.reindex(np.arange(6), method="ffill") # ffill은 앞의 값으로 다음을 채워라라는 의미
print(reindexed)
reindexed  = obj3.reindex(np.arange(6), method="bfill") # bfill은 뒤의 값으로 앞을 채워라라는 의미
print(reindexed)

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object
0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object


In [118]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
print(frame)
frame2 = frame.reindex(index=["a", "b", "c", "d"]) # index를 재정의 할 경우 없던 index에는 값이 NaN이 된다.
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0


In [120]:
print(frame)
states = ["Texas", "Utah", "California"]
frame1 = frame.reindex(columns=states)  # states리스트로 index를 재정의 
print(frame1)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


In [121]:
frame1 = frame.reindex(states, axis="columns") # states리스트로 index를 재정의  
print(frame1)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


In [126]:
print(frame)
print(frame.loc[["a", "d", "c"]])  # 명시적 index 사용
print(frame.loc[["a", "d", "c"], ["California", "Texas"]]) # 명시적 index와 명시적 column명 사용
print(frame.iloc[[0, 2, 1]]) # 암시적 index를 사용
print(frame.iloc[[0, 2, 1], [2, 1]]) # 암시적 index를 사용하는 경우에는 컬럼도 암시적 index를 사용해야 한다.

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a     0      1           2
d     6      7           8
c     3      4           5
   California  Texas
a           2      1
d           8      7
c           5      4
   Ohio  Texas  California
a     0      1           2
d     6      7           8
c     3      4           5
   California  Texas
a           2      1
d           8      7
c           5      4


### 항목 삭제

In [127]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
print(obj)
new_obj = obj.drop("c") # drop함수를 이용해서 해당 index를 삭제할 수 있다.
print(new_obj)
new_obj = obj.drop(["d", "c"])
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
e    4.0
dtype: float64


In [129]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [131]:
new_data = data.drop(index=["Colorado", "Ohio"]) # DataFrame에서는 행당 index행을 삭제할 수 있다.
print(new_data)

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15


In [132]:
new_data = data.drop(columns=["two"]) # columns 키워드를 이용하여 컬럼을 삭제
new_data

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [133]:
new_data = data.drop("two", axis=1)  # axis=1을 이용해서 열을 삭제할 수 있다.
print(new_data)
new_data = data.drop(["two", "four"], axis="columns") # axis="columns" 을 이용해서 열을 삭제할 수 있다.
print(new_data)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15
          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14


### Indexing, Selection, and Filtering

In [134]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
print(obj)
print(obj["b"])
print(obj[1])
print(obj[2:4])
print(obj[["b", "a", "d"]])
print(obj[[1, 3]])
print(obj[obj < 2])

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
1.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64


C:\Users\user\AppData\Local\Temp\ipykernel_13516\1001317559.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[1])
C:\Users\user\AppData\Local\Temp\ipykernel_13516\1001317559.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[[1, 3]])


In [137]:
print(obj.loc[["b", "a", "d"]]) # Series에서 loc사용
print(obj.iloc[[1,0,2]])

b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
a    0.0
c    2.0
dtype: float64


In [138]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
print(obj1)
print(obj2)
print(obj1[[0, 1, 2]]) # Series에서 명시적 index사용
print(obj2[[0, 1, 2]]) # Series에서 암시적 index사용 

2    1
0    2
1    3
dtype: int64
a    1
b    2
c    3
dtype: int64
0    2
1    3
2    1
dtype: int64
a    1
b    2
c    3
dtype: int64


C:\Users\user\AppData\Local\Temp\ipykernel_13516\4241121066.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj2[[0, 1, 2]])


In [139]:
print(obj1.iloc[[0, 1, 2]]) # Series에서 암시적 index사용
print(obj2.iloc[[0, 1, 2]]) # Series에서 암시적 index사용

2    1
0    2
1    3
dtype: int64
a    1
b    2
c    3
dtype: int64


In [140]:
print(obj2.loc["b":"c"]) 

b    2
c    3
dtype: int64


In [141]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [168]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)
print(data["two"]) # 열이름으로 데이터 가져오기
print(data[["three", "one"]])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12


In [145]:
print(data)
print(data[:2] ) # 암시적 index를 이용해서 데이터 가져오기
print(data.iloc[:2] ) # 암시적 index를 이용해서 데이터 가져오기
print(data[data["three"] > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [146]:
print(data < 5) # 팬시 index

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False


In [169]:
data[data < 5] = 0 # True에 해당하는 값을 0으로data[data < 5] = 0 # True에 해당하는 값을 0으로
print(data)

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [148]:
data
data.loc["Colorado"] # 명시적 index사용하여 출력

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [149]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [66]:
data.loc["Colorado", ["two", "three"]] # index와 column의 명시적 사용

In [150]:
print(data.iloc[2]) # 암시적 사용
print(data.iloc[[2, 1]])
print(data.iloc[2, [3, 0, 1]])
print(data.iloc[[1, 2], [3, 0, 1]])

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64
          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7
four    11
one      8
two      9
Name: Utah, dtype: int64
          four  one  two
Colorado     7    0    5
Utah        11    8    9


In [151]:
print(data.loc[:"Utah", "two"])
print(data.iloc[:, :3][data.three > 5])

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64
          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14


In [170]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Integer indexing pitfalls

In [157]:
ser = pd.Series(np.arange(3.))
print(ser)
print(ser[-1]) # 암시적 index를 사용하는 경우에는 오류

0    0.0
1    1.0
2    2.0
dtype: float64


KeyError: -1

In [158]:
print(ser.iloc[-1]) # 암시적 index를 사용하는 경우에는 iloc사용

2.0


In [159]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [160]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

C:\Users\user\AppData\Local\Temp\ipykernel_13516\821879068.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


np.float64(2.0)

In [161]:
ser.iloc[-1]

np.float64(2.0)

In [162]:
ser[:2]

0    0.0
1    1.0
dtype: float64

### Pitfalls with chained indexing

In [171]:
print(data)
data.loc[:, "one"] = 1
print(data)
data.iloc[2] = 5
print(data)
data.loc[data["four"] > 5] = 3
print(data)

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15
          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15
          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3


In [164]:
data.loc[data.three == 5]["three"] = 6 # loc를 사용한 경우에는 [][]를 사용하지 않는 것이 좋다.

C:\Users\user\AppData\Local\Temp\ipykernel_13516\867481848.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three == 5]["three"] = 6


In [174]:
data.loc[data.three == 5, "three"] = 6 # [ , ]로 표시 하는 것이 좋다. 
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

### 산술 연산과 데이터 정렬

In [176]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1, s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64,
 a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [177]:
s1 + s2  # index끼리의 연산임을 알 수 있다.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [178]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [185]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [186]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
print(df1)
print(df2)
print(df1 + df2)

   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN


### 결측값 채움을 활용한 산술 연산 메서드

In [187]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
print(df2)
df2.loc[1, "b"] = np.nan
print(df1)
print(df2)

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [179]:
df1 + df2 # 같은 index와 같은 column끼리의 연산

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [183]:
df1, df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [180]:
df1.add(df2, fill_value=0) # 적어도 한 쪽에만 있어도 없는 곳은 누락된 값(NaN)을 0으로 간주하고 계산 , 둘다 없는 경우에는 NaN

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [184]:
print(1 / df1)
print(df1.rdiv(1))

                 b         c      d
Ohio           inf  1.000000  0.500
Texas     0.333333  0.250000  0.200
Colorado  0.166667  0.142857  0.125
                 b         c      d
Ohio           inf  1.000000  0.500
Texas     0.333333  0.250000  0.200
Colorado  0.166667  0.142857  0.125


In [189]:
print(df1, df2)
new_df = df1.reindex(columns=df2.columns, fill_value=0)
print(df1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0       a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


In [190]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
print(arr[0])
print(arr - arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [191]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
print(frame)
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [192]:
frame - series # 컬럼 index끼리의 연산

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [195]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
print(series2)
print(frame)
print(frame + series2)

b    0
e    1
f    2
dtype: int64
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN


In [199]:
series3 = frame["d"]
print(frame)
print(series3)
print(frame.sub(series3, axis="index")) # axis = 0 이라고 해도 됨, index끼리의 연산

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64
          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0


### Function Application and Mapping

In [200]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
print(frame)
print(np.abs(frame)) # 절대

               b         d         e
Utah   -0.801370 -0.916687 -0.170131
Ohio    0.698571  0.287691 -0.422326
Texas  -0.704569 -1.512803  1.100691
Oregon -0.525919 -0.617613  1.720041
               b         d         e
Utah    0.801370  0.916687  0.170131
Ohio    0.698571  0.287691  0.422326
Texas   0.704569  1.512803  1.100691
Oregon  0.525919  0.617613  1.720041


In [95]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

In [96]:
frame.apply(f1, axis="columns")

In [97]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

In [98]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

In [99]:
frame["e"].map(my_format)

In [ ]:
### Sorting and Ranking

In [202]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
print(obj)
obj1 = obj.sort_index() # index 정렬
print(obj1)

d    0
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    0
dtype: int64


In [204]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
print(frame)
print(frame.sort_index())
print(frame.sort_index(axis="columns")) # column을 가준으로 정렬

       d  a  b  c
three  0  1  2  3
one    4  5  6  7
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4


In [205]:
frame.sort_index(axis="columns", ascending=False) # column을 기준으로 내림차순

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [207]:
obj = pd.Series([4, 7, -3, 2])
print(obj)
print(obj.sort_values()) # 값에 대한 오름차순

0    4
1    7
2   -3
3    2
dtype: int64
2   -3
3    2
0    4
1    7
dtype: int64


In [208]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values() # 오름 차순, NaN값은 마지막

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [209]:
obj.sort_values(na_position="first") #NaN을 위로

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [210]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
print(frame)
print(frame.sort_values("b"))

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1


In [211]:
print(frame.sort_values(["a", "b"]))

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1


In [108]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

In [109]:
obj.rank(method="first")

In [110]:
obj.rank(ascending=False)

In [111]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
frame
frame.rank(axis="columns")

### Axis Indexes with Duplicate Labels

In [212]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [215]:
print(obj.index.is_unique)

False


In [218]:
print(obj["a"])
print(obj["b"])
print(obj["c"])

a    0
a    1
dtype: int64
b    2
b    3
dtype: int64
4


In [219]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])
print(df)
print(df.loc["b"])
print(df.loc["c"])

          0         1         2
a -0.165007 -0.840217 -0.170330
a  0.419331  0.868778 -0.037688
b -1.689466  1.086355  0.774812
b  0.576204  0.293767 -0.714144
c  0.382525 -0.076110  1.721076
          0         1         2
b -1.689466  1.086355  0.774812
b  0.576204  0.293767 -0.714144
0    0.382525
1   -0.076110
2    1.721076
Name: c, dtype: float64


In [220]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["one", "two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [221]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [222]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [225]:
print(df)
print(df.sum(axis="index", skipna=False)) # NaN이 있으면 결과는 NaN axis = 0
print(df.sum(axis="columns", skipna=False)) # axis =1 

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one   NaN
two   NaN
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64


In [227]:
print(df.mean(axis="columns"))  # axis =1 

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64


In [228]:
df.idxmax()

one    b
two    d
dtype: object

In [229]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [230]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [231]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [232]:
price = pd.read_pickle("examples/yahoo_price.pkl") # Python의 객체를 그대로 저장할 수 있는 직렬화 파일 포맷입니다.
volume = pd.read_pickle("examples/yahoo_volume.pkl") # DataFrame, Series, 리스트 등 어떤 Python 객체든 저장하고 복원할 수 있습니다.

In [234]:
price

AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [233]:
returns = price.pct_change() # **연속된 행(시간 순 데이터) 사이의 비율 변화율(%)**을 계산합니다.
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [235]:
print(returns["MSFT"].corr(returns["IBM"]))
print(returns["MSFT"].cov(returns["IBM"]))

0.4997636114415114
8.870655479703545e-05


In [236]:
print(returns.corr())
print(returns.cov())

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000
          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215


In [237]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [238]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [239]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [243]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [244]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [245]:
pd.value_counts(obj.to_numpy(), sort=False)

C:\Users\user\AppData\Local\Temp\ipykernel_13516\164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [246]:
obj
mask = obj.isin(["b", "c"])
mask
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [247]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [248]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [249]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [250]:
result = data.apply(pd.value_counts).fillna(0)
result

C:\Users\user\AppData\Local\Temp\ipykernel_13516\1382616601.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [251]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64