In [2]:
!pip install matplotlib

   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------------------------------ --- 7.3/8.1 MB 37.5 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 34.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 41.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 44.6 MB/s eta 0:00:00

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- -------------

In [4]:
import numpy as np
import pandas as pd

## 7.1 누락된 데이터 처리

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
print(string_data)
print(string_data.isna())

0    aardvark
1         NaN
2        None
3     avocado
dtype: object
0    False
1     True
2     True
3    False
dtype: bool


In [7]:
float_data = pd.Series([1, 2, None], dtype='float64')
print(float_data)
print(float_data.isna())

0    1.0
1    2.0
2    NaN
dtype: float64
0    False
1    False
2     True
dtype: bool


In [9]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
print(data)
data.dropna()

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notna()] # 누락깂 제외하고 출력

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
data.dropna()

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


0    1    2
0  1.0  6.5  3.0

| 값             | 의미                             |
| ------------- | ------------------------------ |
| `"any"` (기본값) | **하나라도 NaN이 있으면** 해당 행 또는 열 제거 |
| `"all"`       | **모두 NaN일 때만** 해당 행 또는 열 제거    |


In [12]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data[4] = np.nan
print(data)
data.dropna(axis="columns", how="all")  # axis = 1 

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
print(df)
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
print(df)

          0         1         2
0  0.364728  1.368665 -0.237930
1  2.119736 -0.028778  0.264963
2  0.109932 -1.305258  1.271057
3  0.946927 -0.679567  0.307836
4 -0.247954 -1.139559 -0.540567
5 -0.941497 -0.944738 -1.215912
6  0.723573 -1.631479  0.126260
          0         1         2
0  0.364728       NaN       NaN
1  2.119736       NaN       NaN
2  0.109932       NaN  1.271057
3  0.946927       NaN  0.307836
4 -0.247954 -1.139559 -0.540567
5 -0.941497 -0.944738 -1.215912
6  0.723573 -1.631479  0.126260


In [19]:
print(df.dropna())
print(df.dropna(thresh=2))

          0         1         2
4 -0.247954 -1.139559 -0.540567
5 -0.941497 -0.944738 -1.215912
6  0.723573 -1.631479  0.126260
          0         1         2
2  0.109932       NaN  1.271057
3  0.946927       NaN  0.307836
4 -0.247954 -1.139559 -0.540567
5 -0.941497 -0.944738 -1.215912
6  0.723573 -1.631479  0.126260


In [20]:
df.fillna(0) # 누락값을 0으로 채우기

0         1         2
0  0.364728  0.000000  0.000000
1  2.119736  0.000000  0.000000
2  0.109932  0.000000  1.271057
3  0.946927  0.000000  0.307836
4 -0.247954 -1.139559 -0.540567
5 -0.941497 -0.944738 -1.215912
6  0.723573 -1.631479  0.126260

In [21]:
df.fillna({1: 0.5, 2: 0}) # 1열은 0.5로, 2열은 0으로

0         1         2
0  0.364728  0.500000  0.000000
1  2.119736  0.500000  0.000000
2  0.109932  0.500000  1.271057
3  0.946927  0.500000  0.307836
4 -0.247954 -1.139559 -0.540567
5 -0.941497 -0.944738 -1.215912
6  0.723573 -1.631479  0.126260

In [22]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
print(df)
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
print(df)

          0         1         2
0 -0.452227 -2.027834 -0.723404
1  0.827866 -0.029194  0.113370
2 -0.204912 -0.031198  1.225992
3 -0.522699  0.676023  0.669478
4  0.363516 -0.808856  0.853929
5  0.103574  0.511107  0.512652
          0         1         2
0 -0.452227 -2.027834 -0.723404
1  0.827866 -0.029194  0.113370
2 -0.204912       NaN  1.225992
3 -0.522699       NaN  0.669478
4  0.363516       NaN       NaN
5  0.103574       NaN       NaN


In [24]:
print(df.fillna(method="ffill")) # 누락값을 앞의 값으로 채우기

          0         1         2
0 -0.452227 -2.027834 -0.723404
1  0.827866 -0.029194  0.113370
2 -0.204912 -0.029194  1.225992
3 -0.522699 -0.029194  0.669478
4  0.363516 -0.029194  0.669478
5  0.103574 -0.029194  0.669478


C:\Users\user\AppData\Local\Temp\ipykernel_12116\2315175252.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method="ffill")) # 누락값을 앞의 값으로 채우기


In [25]:
print(df)
print(df.fillna(method="ffill", limit=2)) # 연속된 NaN 값이 있을 때, 최대 2개까지만 앞의 값으로 채워줍니다

          0         1         2
0 -0.452227 -2.027834 -0.723404
1  0.827866 -0.029194  0.113370
2 -0.204912       NaN  1.225992
3 -0.522699       NaN  0.669478
4  0.363516       NaN       NaN
5  0.103574       NaN       NaN
          0         1         2
0 -0.452227 -2.027834 -0.723404
1  0.827866 -0.029194  0.113370
2 -0.204912 -0.029194  1.225992
3 -0.522699 -0.029194  0.669478
4  0.363516       NaN  0.669478
5  0.103574       NaN  0.669478


C:\Users\user\AppData\Local\Temp\ipykernel_12116\1033594488.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method="ffill", limit=2)) # 연속된 NaN 값이 있을 때, 최대 2개까지만 앞의 값으로 채워줍니다


In [27]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean()) # 열의 평균값으로 채우기

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [28]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [29]:
print(data.duplicated()) # 중복된 행을 판별할 때 사용하는 메서드


0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [30]:
data.drop_duplicates() # 중복된 행 제거

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data[data.duplicated()] # 중복된 행만 가져오기

In [31]:
data["v1"] = range(7)
print(data)
data.drop_duplicates(subset=["k1"]) # 중복 여부를 판단할 때 k1 컬럼만 기준으로 삼겠다는 뜻, k2	v1는 비교 기준에서 제외됨

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6


k1  k2  v1
0  one   1   0
1  two   1   1

In [32]:
data.drop_duplicates(["k1", "k2"], keep="last") # k1과 k2 두 컬럼을 기준으로 중복된 행을 제거
                                                # 중복된 것 중 마지막(last) 행만 남김

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [5]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [5]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [6]:
data["animal"] = data["food"].map(meat_to_animal) # meat_to_animal과 매핑되는 것과 비교.
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [7]:
def get_animal(x):
    return meat_to_animal[x]
data["food"].map(get_animal) # data["food"]의 각 값이 x에 대입

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [8]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [9]:
data.replace(-999, np.nan) # -999는 누락값으로 대체

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [11]:
print(data)
data.replace([-999, -1000], np.nan) # -999와 -1000인경우 누락값으로 

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64


0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [12]:
data.replace([-999, -1000], [np.nan, 0])  # -999는 누락값, -1000은 0으로

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [13]:
data.replace({-999: np.nan, -1000: 0}) # -999는 누락값, -1000은 0으로

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [19]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [16]:
def transform(x):
    return x[:4].upper()

data.index.map(transform) # data의 인덱스를 transform 함수에 전달하여, 각 인덱스의 앞 4글자를 대문자로 변환한 결과를 반환

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [17]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [20]:
data.rename(index=str.title, columns=str.upper) # index=str.title는 index단어의 첫글자를 대문자로, 
                                                # columns=str.upper는 컬럼 단어의 대문자로

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [6]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [8]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [9]:
bins = [18, 25, 35, 60, 100]

In [10]:
age_categories = pd.cut(ages, bins) # ages는 나이고, bins는 구간을 의미하므로 나이가 어느 구간에 속하는지 분석한다,
age_categories
# ( , ]는 수학에서 구간(interval)을 나타내는 표기법
# (는 해당 값은 포함하지 않는다 = exclusive (비포함)
# ]는 해당 값은 포함한다 = inclusive (포함)
# (18, 25] ==  18보다 크고 25 이하인 값

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [27]:
age_categories.codes # age_categories.codes	각 값이 속한 범주의 정수 코드 (0부터 시작)
# ages[0] = 20 → (18, 25] → 코드 0
# ages[3] = 27 → (25, 35] → 코드 1
# ages[6] = 27 → (35, 60] → 코드 2
# ages[8] = 61 → (60, 100] → 코드 3

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [28]:
age_categories.categories # 범주 구간으로 나눈 결과 (Interval)

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [11]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [12]:
pd.value_counts(age_categories) # 각 구간(범주, 카테고리)에 해당하는 값이 몇 개인지 세어주는 함수

C:\Users\user\AppData\Local\Temp\ipykernel_14312\4185733935.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories) # 각 구간(범주, 카테고리)에 해당하는 값이 몇 개인지 세어주는 함수


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [36]:
pd.cut(ages, bins, right=False)
# 기본값은 right=False 임.
# right=False인 경우 [18, 25)이 된다 , 즉 18은 포함하고, 25는 포함하지 않는다

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [37]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)
# 나이 데이터 ages를 bins 기준으로 구간을 나누고,
# 각 구간에 이름(라벨)을 붙임

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [39]:
data = np.random.uniform(size=20)
data

array([0.97139673, 0.21843765, 0.53484679, 0.85080704, 0.01159107,
       0.6099567 , 0.87039697, 0.46625657, 0.21943123, 0.24081485,
       0.0275335 , 0.35548064, 0.24361804, 0.23360282, 0.79623008,
       0.32733669, 0.00484921, 0.14700916, 0.12843508, 0.41436029])

In [40]:
pd.cut(data, 4, precision=2)
# bins=4 → data의 최솟값~최댓값 범위를 4등분
# precision=2 → 경계 값 소수점 둘째 자리까지 반올림

[(0.73, 0.97], (0.0039, 0.25], (0.49, 0.73], (0.73, 0.97], (0.0039, 0.25], ..., (0.25, 0.49], (0.0039, 0.25], (0.0039, 0.25], (0.0039, 0.25], (0.25, 0.49]]
Length: 20
Categories (4, interval[float64, right]): [(0.0039, 0.25] < (0.25, 0.49] < (0.49, 0.73] < (0.73, 0.97]]

In [42]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2) # qcut은 데이터를 동일한 개수의 구간(quantile)으로 나누는 함수입니다.
                                          # 4는 4개의 구간, 즉 사분위(quartile) 로 나눔
print(quartiles)
pd.value_counts(quartiles)

[(-0.64, 0.014], (-2.8899999999999997, -0.64], (-2.8899999999999997, -0.64], (0.014, 0.65], (-2.8899999999999997, -0.64], ..., (0.014, 0.65], (0.65, 3.07], (0.65, 3.07], (0.65, 3.07], (0.014, 0.65]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.8899999999999997, -0.64] < (-0.64, 0.014] < (0.014, 0.65] < (0.65, 3.07]]


C:\Users\user\AppData\Local\Temp\ipykernel_14312\95998493.py:5: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-2.8899999999999997, -0.64]    250
(-0.64, 0.014]                  250
(0.014, 0.65]                   250
(0.65, 3.07]                    250
Name: count, dtype: int64

In [43]:
# 각 4사분위에 데이터의 수를 출력
print(pd.qcut(data, [0, 0.25, 0.5, 0.75, 1.]).value_counts())
# 원하는 범위의 데이터의 갯수 
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.88, -0.638]     250
(-0.638, 0.0137]    250
(0.0137, 0.655]     250
(0.655, 3.07]       250
Name: count, dtype: int64


(-2.88, -1.224]     100
(-1.224, 0.0137]    400
(0.0137, 1.379]     400
(1.379, 3.07]       100
Name: count, dtype: int64

In [62]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
print(data)
data.describe()

            0         1         2         3
0    0.311440 -0.379794 -0.542488  1.011806
1   -1.095622  0.521713 -1.393550  0.803063
2    0.747856  0.743789 -1.136067 -1.113813
3   -0.454568  0.599409 -0.226868 -0.204075
4   -1.954757  0.977413  1.704668  0.995966
..        ...       ...       ...       ...
995 -0.414996 -2.171590  1.518600 -0.171340
996 -0.828293 -0.447862 -0.171020 -1.195785
997  0.034359 -1.006385  0.330920  0.542419
998 -0.436400 -0.814972 -1.138506  0.326651
999  1.702705 -0.306541  1.160354  0.296668

[1000 rows x 4 columns]


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.006991    -0.028599     0.006792     0.006976
std       0.990806     1.024133     0.995654     0.965445
min      -3.044506    -3.043017    -3.183126    -3.486857
25%      -0.616256    -0.749239    -0.689625    -0.650419
50%       0.008464    -0.025388    -0.003458    -0.011525
75%       0.671999     0.665881     0.673515     0.668107
max       2.930509     3.288600     3.081330     2.681563

In [63]:
col = data[2]
print(col)
col[col.abs() > 3] # 절대값이 3이상인 행만 출력

0     -0.542488
1     -1.393550
2     -1.136067
3     -0.226868
4      1.704668
         ...   
995    1.518600
996   -0.171020
997    0.330920
998   -1.138506
999    1.160354
Name: 2, Length: 1000, dtype: float64


221   -3.004656
326   -3.183126
542    3.022409
757    3.081330
Name: 2, dtype: float64

In [64]:
data[(data.abs() > 3).any(axis="columns")]  # 해당 행에 절댓값이 3보다 큰 값이 있는 행만 출력

0         1         2         3
40   0.054714 -3.043017 -0.880743  1.436243
115  0.588443  0.522831 -0.784739 -3.486857
221  0.642260  0.584582 -3.004656 -0.393105
326  0.600234 -0.256472 -3.183126  0.702965
537  0.676146  3.288600 -0.132577  0.438367
542  0.313332 -0.715007  3.022409  0.325209
757  0.495159  1.231153  3.081330  2.219055
889 -3.035722  0.154002 -0.935116 -0.576489
954 -3.044506  2.013311  0.758065 -0.156129

| x  | `np.sign(x)` |
| -- | ------------ |
| 양수 | `+1`         |
| 음수 | `-1`         |
| 0  | `0`          |

### np.sign(data) * 3 <br />
data의 부호는 유지하면서, 값의 크기는 ±3으로 고정.<br />
data = -4.5  →  np.sign(-4.5) * 3 = -1 * 3 = -3<br />
data = 5.8   →  np.sign(5.8) * 3  = +1 * 3 = 3<br />

In [65]:
data[data.abs() > 3] = np.sign(data) * 3

In [74]:
data[(data.abs() == 3).any(axis="columns")] # 바뀐값을 확인해보자.

0         1         2         3
40   0.054714 -3.000000 -0.880743  1.436243
115  0.588443  0.522831 -0.784739 -3.000000
221  0.642260  0.584582 -3.000000 -0.393105
326  0.600234 -0.256472 -3.000000  0.702965
537  0.676146  3.000000 -0.132577  0.438367
542  0.313332 -0.715007  3.000000  0.325209
757  0.495159  1.231153  3.000000  2.219055
889 -3.000000  0.154002 -0.935116 -0.576489
954 -3.000000  2.013311  0.758065 -0.156129

In [75]:
np.sign(data).head() # 양수면 1, 음수면 -1 , 0은 0

0    1    2    3
0  1.0 -1.0 -1.0  1.0
1 -1.0  1.0 -1.0  1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4 -1.0  1.0  1.0  1.0

In [76]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
print(df)
sampler = np.random.permutation(5)
print(sampler)

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
[3 1 0 4 2]


In [78]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [79]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [80]:
column_sampler = np.random.permutation(7)
column_sampler

array([4, 6, 3, 2, 1, 0, 5], dtype=int32)

In [81]:
df.take(column_sampler, axis="columns")

4   6   3   2   1   0   5
0   4   6   3   2   1   0   5
1  11  13  10   9   8   7  12
2  18  20  17  16  15  14  19
3  25  27  24  23  22  21  26
4  32  34  31  30  29  28  33

In [90]:
df.sample(n=3) # 무작위로 n개의 행(row)를 샘플링

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [91]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace=True) # replace=True는 복원 추출 (한 번 뽑은 데이터도 다시 뽑힐 수 있음, 즉 중복 허용)

4    4
4    4
4    4
0    5
4    4
4    4
4    4
0    5
2   -1
2   -1
dtype: int64

In [92]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
print(df)
pd.get_dummies(df["key"], dtype=float) # 원-핫 인코딩(one-hot encoding) : 문자를 0,1로 표현
                                       # a : 100 , b:010, c:001 

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5


a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [94]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)
print(dummies) # 원-핫 엔코딩 데이터
df_with_dummy = df[["data1"]].join(dummies) # 각각의 행에 원-핫 엔코딩된 데이터를 붙이기
df_with_dummy

   key_a  key_b  key_c
0    0.0    1.0    0.0
1    0.0    1.0    0.0
2    1.0    0.0    0.0
3    0.0    0.0    1.0
4    1.0    0.0    0.0
5    0.0    1.0    0.0


data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [97]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("https://raw.githubusercontent.com/SoongMoo/soldesk20250614/refs/heads/main/datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python") # names은 컬럼명
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [98]:
dummies = movies["genres"].str.get_dummies("|") # genres애 있는 데이터를 "|"를 가준으로 원-핫 엔코딩을 한다.
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [112]:
np.random.seed(12345) # to make the example repeatable
values = np.random.uniform(size=10) # 0 이상 1 미만의 실수(float)를 균등 분포(uniform distribution)를 따라 무작위로 10개 생성하는 함수
print(values)
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503 0.5955447
 0.96451452 0.6531771  0.74890664 0.65356987]


(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

pd.get_dummies(pd.cut(values, bins))은?
   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           1           0           0           0           0
1           0           0           0           0           1
2           0           0           1           0           0
3           0           0           0           1           0
...

In [113]:
s = pd.Series([1, 2, 3, None])
s
s.dtype

dtype('float64')

In [114]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s
s.isna()
s.dtype

Int64Dtype()

In [115]:
s[3]
s[3] is pd.NA

True

In [116]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [117]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [119]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
print(df)
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True


A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [120]:
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [121]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [122]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [123]:
"::".join(pieces)

'a::b::guido'

In [129]:
print(val)
"guido" in val
print(val.index(","))
print(val.find(":"))

a,b,  guido
1
-1


In [125]:
val.index(":")

ValueError: substring not found

In [126]:
val.count(",")

2

In [127]:
val.replace(",", "::")
val.replace(",", "")

'ab  guido'

In [131]:
import re
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [132]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [133]:
regex.findall(text)

['    ', '\t ', '  \t']

In [76]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [77]:
regex.findall(text)

In [78]:
m = regex.search(text)
m
text[m.start():m.end()]

In [79]:
print(regex.match(text))

In [80]:
print(regex.sub("REDACTED", text))

In [81]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [82]:
m = regex.match("wesm@bright.net")
m.groups()

In [83]:
regex.findall(text)

In [84]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

In [85]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data
data.isna()

In [86]:
data.str.contains("gmail")

In [87]:
data_as_string_ext = data.astype('string')
data_as_string_ext
data_as_string_ext.str.contains("gmail")

In [88]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

In [89]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches
matches.str.get(1)

In [90]:
data.str[:5]

In [91]:
data.str.extract(pattern, flags=re.IGNORECASE)

In [92]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values
pd.unique(values)
pd.value_counts(values)

In [93]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
values
dim

In [94]:
dim.take(values)

In [134]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [135]:
fruit_cat = df['fruit'].astype('category') # category는 pandas의 자료형
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [137]:
c = fruit_cat.array
print(c)
type(c)

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']


pandas.core.arrays.categorical.Categorical

In [138]:
print(c.categories)
print(c.codes)

Index(['apple', 'orange'], dtype='object')
[0 1 0 0 0 1 0 0]


In [139]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [142]:
df['fruit'] = df['fruit'].astype('category')
print(df["fruit"])
print(df.info())

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype   
---  ------     --------------  -----   
 0   basket_id  8 non-null      int64   
 1   fruit      8 non-null      category
 2   count      8 non-null      int64   
 3   weight     8 non-null      float64 
dtypes: category(1), float64(1), int64(2)
memory usage: 456.0 bytes
None


In [147]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

### ==================== 이하는 같은 네용 ==============================

In [148]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [149]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [150]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [151]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [152]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [153]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [154]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())
results

C:\Users\user\AppData\Local\Temp\ipykernel_14312\2483392743.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [155]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [157]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [158]:
categories = labels.astype('category')

In [159]:
labels.memory_usage(deep=True)
categories.memory_usage(deep=True)

10000512

In [160]:
%time _ = labels.astype('category')

CPU times: total: 531 ms
Wall time: 545 ms


In [114]:
%timeit labels.value_counts()
%timeit categories.value_counts()

In [161]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [162]:
cat_s.cat.codes
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [163]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [164]:
cat_s.value_counts()
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [165]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [167]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [168]:
pd.get_dummies(cat_s, dtype=float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0

In [123]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS